apiVersion: apps/v1
kind: Deployment
metadata:
  name: informa-poc
  labels:
    app: informa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: informa
  template:
    metadata:
      labels:
        app: informa
    spec:
    terminationGracePeriodSeconds: 30
      containers:
      - name: informa
        image: informa1048135.azurecr.io/informa-poc:v1
        imagePullPolicy: "Always"
      imagePullSecrets:
      - name: acr-auth
        ports:
        - containerPort: 90
