kind: Service
apiVersion: v1
metadata:
  name: informa-cicd
spec:
  selector:
    app: informa-poc
    tier: backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    nodePort: 32131
    port: 3000
